blank_issues_enabled: false
contact_links:
  - name: BigTreeTech Facebook group
    url: https://www.facebook.com/groups/505736576548648
    about: Please ask and answer questions here.
  - name: BigTreeTech Subreddit
    url: https://www.reddit.com/r/BIGTREETECH/
    about: Please ask and answer questions here.
