/**
 * Icon Keywords Generation
 * Usage: X_SMALLICON(VALUE)
 * 'VALUE' is the keyword name without the 'SMALLICON_'
 *
 * Description: https://en.wikipedia.org/wiki/X_Macro
 *
 * After changing/adding/removing an icon, change the ICON_FLASH_SIGN in Settings.h
 */

//X_SMALLICON (INC)
//X_SMALLICON (DEC)
//X_SMALLICON (NUMPAD)
// After changing/adding/removing an icon, change the ICON_FLASH_SIGN in Settings.h
