name: Test Configuration
on: push

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install Platform IO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build 
        run: platformio run --target BIGTREE_TFT35_V3_0     
      - name: Build
        run: platformio run --target BIGTREE_TFT35_V2_0
      - name: Build
        run: platformio run --target BIGTREE_TFT35_V1_2
      - name: Build
        run: platformio run --target BIGTREE_TFT35_V1_1
      - name: Build
        run: platformio run --target BIGTREE_TFT35_V1_0
      - name: Build
        run: platformio run --target BIGTREE_TFT28_V1_0
      - name: Build
        run: platformio run --target BIGTREE_TFT24_V1_1
